version: '3'

services:
  database:
    image: taimoora91/misedb:0.8
    container_name: database
    networks:
      udn_bridge:
        ipv4_address: 10.10.10.2
    volumes:
      - database_data:/var/lib/mysql

  miseweb:
    image: taimoora91/miseweb:latest  # Use the custom image with Docker CLI
    container_name: miseweb
    networks:
      udn_bridge:
        ipv4_address: 10.10.10.3
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Bind Docker socket
      - shared_data:/var/www/html/mise/v0.1  # Add shared volume
      - landscape_data:/root/ise-landscape/mise  # Add second shared volume

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:  # Setting environment variables for phpMyAdmin
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=C1sc0123@
    networks:
      udn_bridge:
        ipv4_address: 10.10.10.4
    ports:
      - "9443:80"

  misepy:
    image: taimoora91/misepy:0.4
    container_name: misepy
    networks:
      udn_bridge:
        ipv4_address: 10.10.10.5
    volumes:
      - shared_data:/var/www/html/mise/v0.1  # Add shared volume
      - landscape_data:/root/ise-landscape/mise  # Add second shared volume

networks:
  udn_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

volumes:
  database_data:
  shared_data:
  landscape_data:
